import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test

/*
 * This Java source file was generated by the Gradle 'init' task.
 */


class LibraryTest {
    @Test
    fun testSomeLibraryMethod() {
        Assertions.assertTrue(someLibraryMethod(), "someLibraryMethod should return 'true'")
    }
}
