/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test
import org.junit.Assert.*

class LibraryTest {
    @Test
    fun testSomeLibraryMethod() {
        assertTrue("someLibraryMethod should return 'true'", someLibraryMethod())
    }
}
